// <auto-generated />
using MarketPlaceApp.Domain.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarketPlaceApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200328044943_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarketPlaceApp.Domain.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "UE4 - Align Actors in Editor using tools like in 3ds max",
                            ImageURL = "https://cdn1.epicgames.com/ue/product/Featured/AssetBuilderToolsFreeDemo_featured-894x488-c332a75f9f46e558ffe6bbe3588b5d08.png",
                            Tag = "Align, Snap, Construction",
                            Title = "AssetBuilder Tools Free Demo"
                        },
                        new
                        {
                            Id = 2,
                            Description = "56 PBR Fabric Materials - Game and Arch Viz Ready, ideal for both environments and characters. Created at 4K resolution",
                            ImageURL = "https://cdn1.epicgames.com/ue/product/Featured/FabricMaterials56Pack_featured-894x488-8c9cb21c4608e5e6aeb9e92ac352cbb6.png",
                            Tag = "Materials, PBR, Textures",
                            Title = "Fabric Materials - 56 Pack"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Package contains over 350 models to build stylized dungeons for top-down and first-person games.",
                            ImageURL = "https://cdn1.epicgames.com/ue/item/MultistoryDungeons_Image_894X488-896x488-0bdc200ab21cf23c07a9c5b676a6d996.png",
                            Tag = "Dungeons, Fantasy, Low Poly, Stylized, Modular, RPG",
                            Title = "Multistory Dungeons"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This project includes a set of modular meshes and simple blueprint setups to create a subway train. All assets, materials, and vfx created in the Unreal Engine at production ready quality. Each asset was created for realistic AAA quality visuals, style, and budget.",
                            ImageURL = "https://cdn1.epicgames.com/ue/product/Screenshot/subwaytrain_screenshot_01-1920x1080-9336094e9e4eded2c797621b34eb2ac8.png",
                            Tag = "Realistic, City, Horror, Metro",
                            Title = "City Subway Train - Modular"
                        },
                        new
                        {
                            Id = 5,
                            Description = "‘Freedom’ is a bold, uplifting orchestral track, imbued with ideas of exploration, and the pioneering spirit.",
                            ImageURL = "https://img.youtube.com/vi/8wQd6G1ONTg/maxresdefault.jpg",
                            Tag = "Orchestral, Uplifting, Exploration",
                            Title = "Freedom"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A 2019 remaster of an old track! ‘Ashes’ is a simple, uplifting orchestral track with acoustic drums and strings. The new version has more emphasis on solo strings (violin and cello).",
                            ImageURL = "https://img.youtube.com/vi/dOkZKq5o99w/maxresdefault.jpg",
                            Tag = "Orchestral, Uplifting",
                            Title = "Ashes of a Fallen Year - Remaster"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Elevator music, pure and simple. Three versions are provided: Full Mix, EQ’d (for the elevator speaker experience), and EQ’d + Less Drums (heard above), which has a simpler, more comedic vibe.V",
                            ImageURL = "http://www.scottbuckley.com.au/wp-content/uploads/scott-wall2-flipped-fade3.jpg",
                            Tag = "Elevator, Samba, Jazzy, Relaxing",
                            Title = "Skyscraper Samba"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sweeping orchestra, with a touch of sadness, a pinch of melancholy, but a smidgeon of hope for balance – a modern tone poem for the trials of overcoming adversity. A simple, distorted synth helps drive the orchestra forward.",
                            ImageURL = "https://img.youtube.com/vi/fMx5roxJ7Uk/maxresdefault.jpg",
                            Tag = "Sad, Orchestra",
                            Title = "Ascension"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Simple piano and strings, evoking the naivety of childhood.",
                            ImageURL = "https://img.youtube.com/vi/0JhMDxp3LFA/maxresdefault.jpg",
                            Tag = "Piano, Happy",
                            Title = "Childhood"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ambient electronics, strings and solo cello, melding into an amorphous tonal explorational soundscape. I’ve also included a ‘No Cello’ mix, which transforms the track into atmospheric underscore.",
                            ImageURL = "https://img.youtube.com/vi/kbTClxgehrQ/maxresdefault.jpg",
                            Tag = "Ambient, Dark",
                            Title = "Computations in a Snowstorm"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Darker ambient piano – subtle thriller vibes, with a simpler piano theme which should hopefully work well as underscore. Also included is a ‘no melody’ alternative mix.",
                            ImageURL = "https://img.youtube.com/vi/TO5eGVihmN0/maxresdefault.jpg",
                            Tag = "Ambient, Dark, Piano",
                            Title = "Intervention"
                        },
                        new
                        {
                            Id = 12,
                            Description = "A cinematic re-orchestration of ‘O Come All Ye Faithful’, with sweeping strings, brass and percussion. Merry Christmas guys! Thanks for an amazing year.",
                            ImageURL = "https://img.youtube.com/vi/Or0AdFdwICA/maxresdefault.jpg",
                            Tag = "Chistmas, Xmas, Orchestral",
                            Title = "‘O Come All Ye Faithful"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A heartfelt reflection of the snowy darkness of Midwinter (at least of what it’s like here in Sweden!). Simple layered pianos, percussive and sustained strings, and synths.",
                            ImageURL = "https://img.youtube.com/vi/2N6LRMFT7_A/maxresdefault.jpg",
                            Tag = "Snow, Winter, Piano, Synth, Strings",
                            Title = ""
                        },
                        new
                        {
                            Id = 14,
                            Description = "A simple, moody extrapolation of a piano improvisation, featuring atmospheric strings. Slightly uplifting, slightly melancholy.",
                            ImageURL = "https://img.youtube.com/vi/ZUua4pp2PKw/maxresdefault.jpg",
                            Tag = "Moody, Piano, Strings",
                            Title = "Extrapolation"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
